# Generated by Django 4.2 on 2024-03-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.Field(verbose_name='手机号')),
                ('nickname', models.Field(verbose_name='昵称')),
                ('sex', models.Field(verbose_name='性别')),
                ('birth_year', models.Field(verbose_name='出生')),
                ('birth_month', models.Field(verbose_name='出生')),
                ('birth_day', models.Field(verbose_name='出生')),
                ('avatar', models.Field(verbose_name='手机号')),
                ('location', models.Field(verbose_name='手机号')),
            ],
        ),
    ]
