# Generated by Django 4.2 on 2024-03-14 12:54

from django.db import migrations, models
import libs.orm


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('bj', '北京'), ('sh', '上海'), ('sz', '深圳'), ('gz', '广州'), ('wh', '武汉'), ('xa', '西安'), ('cd', '成都')], max_length=8, verbose_name='目标城市')),
                ('dating_sex', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=8, verbose_name='匹配的性别')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=50, verbose_name='最大交友年龄')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_match', models.BooleanField(default=True, verbose_name='不让匹配的人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
            bases=(models.Model, libs.orm.ModelMixin),
        ),
    ]
